name: SonarCloud

on:
  push:
    branches: [prod]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run tests and generate coverage
        run: npm run test
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.organization=reda1mg
            -Dsonar.projectKey=reda1mg_kempo-bloc
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
